### ISSUE TITLE
I already use 

### ISSUE THREAD

**Issue by editinghero** [neeleshpandey/MassMailing#1]
#1  use an online company provider
you can contact me at

*@gfx-eh.tech

![Screenshot_20211125-131223](https://user-images.githubusercontent.com/69391940/143399927-4e0585a6-abf4-4dac-9a90-ec1927bae420.jpg)
 +I use mailgun
sendiblue
Sendgrid

And mainly
Improve mx
This e-mails which i use is from improve mx 

Then why any one will your
😂😂😂😂😂

Sorry for this much tatti in this post
Take it as a joke🃏🤡🤣🤣🤣
What you made is nice

**Comment by neeleshpandey** [comment]
😂

**Comment by neeleshpandey** [comment]
Well, Yeh allag kaam keh liye hai
hum iska use Participants ko invitation Bhejne keh liye karte hai
through this we send thousands of Mail's, individually<With HTML>

**Comment by editinghero** [comment]
You will close ill open

**Comment by editinghero** [comment]
After 3 months got active

**Comment by editinghero** [comment]
Very busy

**Comment by neeleshpandey** [comment]
Are Are😂
